Repository solidusio/solidus_paypal_commerce_platform, pull requests merged in 2020-07, with the labels that each got.

#54 Display paypal email to customer on confirmation
  app/assets/javascripts/spree/frontend/solidus_paypal_commerce_platform/button_actions.js
  app/overrides/spree/payments/payment/add_paypal_email_to_payment.rb
  config/locales/en.yml
  db/migrate/20200702122528_add_email_to_paypal_commerce_platform_sources.rb
  lib/solidus_paypal_commerce_platform/engine.rb
  lib/views/backend/spree/admin/payments/source_views/_paypal_commerce_platform.html.erb
  lib/views/frontend/solidus_paypal_commerce_platform/payments/_payment.html.erb
  lib/views/frontend/spree/checkout/payment/_paypal_commerce_platform.html.erb
  spec/features/frontend/checkout_spec.rb
Labels: enhancement

#56 Send amount of payment to PayPal on capture
  app/models/solidus_paypal_commerce_platform/gateway.rb
  spec/models/solidus_paypal_commerce_platform/payment_method_spec.rb
Labels: solidus admin

#58 Use the ORB definition of lint-code
  .circleci/config.yml
Labels: chore

#57 Add deface to deps
  solidus_paypal_commerce_platform.gemspec
Labels: bug

#50 Add configuration options to SolidusPaypalCommercePlatform
  README.md
  app/controllers/solidus_paypal_commerce_platform/shipping_rates_controller.rb
  app/controllers/solidus_paypal_commerce_platform/wizard_controller.rb
  app/models/solidus_paypal_commerce_platform/gateway.rb
  app/models/solidus_paypal_commerce_platform/wizard.rb
  app/views/solidus_paypal_commerce_platform/admin/payment_methods/_paypal_wizard.html.erb
  lib/solidus_paypal_commerce_platform.rb
  lib/solidus_paypal_commerce_platform/client.rb
  lib/solidus_paypal_commerce_platform/configuration.rb
  spec/lib/solidus_paypal_commerce_platform/configuration_spec.rb
Labels: chore

#59 Verify email address is verified before allowing payment method to be available
  app/controllers/solidus_paypal_commerce_platform/wizard_controller.rb
  app/models/solidus_paypal_commerce_platform/payment_method.rb
  app/overrides/spree/admin/payment_methods/form/insert_email_verification_notification.rb
  app/views/solidus_paypal_commerce_platform/admin/payment_methods/_available_to_users.html.erb
  config/locales/en.yml
Labels: chore, solidus admin

#81 Cleanup
  .gitignore
  README.md
  app/models/solidus_paypal_commerce_platform/gateway.rb
  bin/sandbox
  db/migrate/20200521190038_add_paypal_commerce_platform_sources.rb
  db/migrate/20200702122528_add_email_to_paypal_commerce_platform_sources.rb
  lib/solidus_paypal_commerce_platform/factories.rb
  solidus_paypal_commerce_platform.gemspec
  spec/factories/paypal_payment_method_factory.rb
  spec/spec_helper.rb
Labels: chore
